### ISSUE TITLE
请问这有提交到npm吗？能否在浏览器端使用？

### ISSUE THREAD

**Issue by litice-wen** [mmzp/sql-parser#2]

**Comment by mmzp** [comment]
有构建一个 npm 包，`npm i @k-tavern/sql-parser`

浏览器端的兼容我需要再看下怎么支持

**Comment by litice-wen** [comment]
好的，谢谢大佬

**Comment by mmzp** [comment]
我用 rollup.js 构建了一个可用在浏览器端直接引用的目标文件，有需要的话可以通过 `https://cdn.jsdelivr.net/gh/mmzp/sql-parser@master/sql-parser.min.js` 直接引用。
